### ISSUE TITLE
clearer explanation of arguments of corner()

### ISSUE THREAD

**Issue by marcellastro** [cristobal-sifon/plottools#1]
While explaining the arguments of corner(), you write
 X         : array-like
                  all posterior parameters. Can also be the outputs of
                  more than one chain, given as an array of arrays of models
                  (e.g., X = [[A1, B1, C1], [A2, B2, C2]])
I suppose it might help to explain that A B C are parameters, whereas 1 and 2 refers to the chains. This is perhaps counter intuitive at the moment because the example provided in this repository deals with 2 parameters and 3 chains.

**Comment by cristobal-sifon** [comment]
fixed that. Please let me know if there are any other unclear parameters otherwise I'll close this one.

**Comment by marcellastro** [comment]
see issue #2 about bbox_to_anchor.
otherwise you might close this issue.

**Comment by cristobal-sifon** [comment]
I'll close this one then.
